name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app api

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Start FastAPI app with uvicorn
        run: |
          pip install uvicorn
          nohup uvicorn app.main:app --host 0.0.0.0 --port 10000 &
          
